### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by hckhanh** [yahoo/react-intl#933] opened 2017-04-26 03:37 UTC
Hi there,
When I upgrade to the newer version of React (15.5.4). There are some warnings about [PropTypes](https://facebook.github.io/react/docs/typechecking-with-proptypes.html).
Now, Facebook refer to the [prop-types](https://github.com/reactjs/prop-types) package instead of built-in PropTypes in main package.

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead
```

**Comment by hatchette** [comment] 2017-04-26 08:45
This is duplicate of #922

**Comment by MichaelDeBoey** [comment] 2017-05-04 09:00
Closed by #918

**Closed** 2017-05-06 15:06 UTC
