### ISSUE TITLE
FormattedMessage should process classNames prop

### ISSUE THREAD

**Issue by mschipperheyn** [yahoo/react-intl#924] opened 2017-04-12 15:47 UTC
Currently, it doesn't. Makes it a little more convenient to use in combination with stuff like styled-components.

**Comment by ghostd** [comment] 2017-04-13 06:17
Duplicate of #913 and #854

**Comment by okuryu** [comment] 2017-07-22 10:16
Duplicate of #854.

**Closed** 2017-07-22 10:16 UTC
Labels: duplicate
