### ISSUE TITLE
getting Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by deezahyn** [yahoo/react-intl#123] opened 2015-06-13 00:47 UTC
seems like I'm getting an error
```
var oldReact = global.React;
global.React = require('react');
...
```

**Comment by deezahyn** [comment] 2015-06-13 00:49
http://take.ms/Cvuti

**Comment by caridy** [comment] 2015-06-15 16:52
this sounds like you're trying to load react-intl incorrectly. Can you provide more details?

**Comment by deezahyn** [comment] 2015-07-03 13:26
if I already have react in my node_modules, this breaks,
 because for some reason it can't see react.  I have to manually go to node_modules/react-intl and do a npm install react there in order for it to work.

**Comment by caridy** [comment] 2015-07-07 01:13
dupe of https://github.com/yahoo/react-intl/issues/79

**Closed by caridy** 2015-07-07 01:13 UTC
Labels: needs info, support

**Comment by deezahyn** [comment] 2015-07-07 16:08
@caridy mine is 25 days old #128 is just 15 days old, shouldn't be the #128 be the dupee and not this?

**Comment by deezahyn** [comment] 2015-07-07 16:12
also @caridy is this fixed, #128 seems to be closed?  If you guys don't intend to fix this at least add a note in the readme that you need to manually npm install react inside react-intl in your node modules.

**Comment by ericf** [comment] 2015-09-11 22:18
See: #162

**Comment by lanceschi** [comment] 2015-10-18 20:14
Hi @caridy,

I'm getting in the javascript browser console the infamous: "Uncaught ReferenceError: React is not defined" by simply adding this import line:

```javascript
import {IntlProvider, FormattedNumber, FormattedPlural} from 'react-intl';
```

I'm using  ```"react": "^0.14.0"``` and I've installed ```react-intl``` npm through command line:
```shell
sudo npm react-intl@next --save
```

My updated package.json reports:
```json
"dependencies": {
  "react": "^0.14.0",
  "react-intl": "^2.0.0-pr-3"
  ...
}
```

Any advice appreciated. Thanks.

**Comment by lanceschi** [comment] 2015-10-19 19:27
Nevermind. In order to boost the browserify task during development I use the [browserify-incremental](https://www.npmjs.com/package/browserify-incremental) package.

Today I manually deleted the incremental cache-file just to be sure. Now everything works as expected. Hope this could help someone.

**Comment by CedricLor** [comment] 2016-01-11 15:38
Hi. Just had a very similar issue. Though not using browserify incremental, using browserify with watchify.

I deleted the bundle file and everything starting working properly in case anyone runs into a similar issue.
