### ISSUE TITLE
FormattedMessage render returns undefined

### ISSUE THREAD

**Issue by jonashartwig** [yahoo/react-intl#947] opened 2017-05-17 06:03 UTC
Hi,

we just changed from version 2.1.3 to 2.3.0. It went smoothly. However if i link some packages together I do now get an error I did not get with the previous version. React tells me that the render version of FormattedMessage has an invalid component: undefined. That only happens if i use npm link.

Any ideas of what i am doing wrong?

Regards

**Comment by ghostd** [comment] 2017-05-18 11:43
I think you could check your imports (check you didnt forget the braces) or something like that.

**Comment by okuryu** [comment] 2017-05-18 13:38
Could you provide repro?

**Comment by okuryu** [comment] 2017-09-13 13:16
closing, please file an issue if you still have any problems.

**Closed by okuryu** 2017-09-13 13:16 UTC
Labels: needs info

**Comment by phistuck** [comment] 2018-01-14 08:48
The problem is simple -
- Component Foo has react-intl@2.3.0 code embedded in its artifact (dist/x.min.js has the actual react-intl code in it) and uses FormattedMessage.
- The application uses react-intl@2.1.0 and renders component Foo.
Result -
The aforementioned error.
Solution -
- Downgrade the react-intl version in Foo (not recommended)
- Upgrade the react-intl version in the application (generally recommended)
- Either exclude the react-intl code from Foo, or split Foo to foo.min.js and vendor.min.js and only vendor.min.js will include the react-intl code, which will not be included when using Foo, unless it is explicitly imported/included.

**Comment by phistuck** [comment] 2018-01-14 09:53
I think this may count as a backward compatibility break, though. Perhaps a default element type should be added instead of relying on something that may not exist in the context?
