### ISSUE TITLE
Separators not working in Firefox

### ISSUE THREAD

**Issue by almoraleslopez** [yahoo/react-intl#143] opened 2015-08-11 10:00 UTC
Hello.

I have react-intl working fine on Chrome and Internet Explorer, but have a problem with Firefox when trying to print a formatted number, the thousands separators (dots for locale "es") are not showing at the DOM and instead of a dot I have a blank space.

My configuration:
React 0.13.1 + React Intl 1.2.0 + Gulp + Webpack + React Router

In the main file I have a intlData variable passed as props in the render. All formatted messages, numbers, etc are working properly, so I believe the configuration is not the problem. All is tested with locale "es". 

In the IntlData I pass  the next structure:

```
var intlData = {
    "locales": "es",
    "messages": {... }
};
```

Any idea where is the problem?

**Comment by caridy** [comment] 2015-08-11 14:16
@almoraleslopez it sounds like a bug in firefox, here is what I see:

```
// chrome
> new Intl.NumberFormat('es').format(12345)
"12.345"
> new IntlPolyfill.NumberFormat('es').format(12345)
"12.345"

// firefox
> new Intl.NumberFormat('es').format(12345)
"12 345"
> new IntlPolyfill.NumberFormat('es').format(12345)
"12.345"
```

Also, I can confirm that CLDR data matches Chrome behavior:
https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/es.json#L2180-L2188

Feel free to open a bug on firefox. I'm closing this one since this is not an issue with this pkg.

**Closed by caridy** 2015-08-11 14:16 UTC
Labels: needs info

**Comment by almoraleslopez** [comment] 2015-08-11 18:28
@caridy thanks for your answer. 

I've just open an issue on Firefox. I'll write back here if it is solved in the near future.
