### ISSUE TITLE
Move react to peerDependencies

### ISSUE THREAD

**Issue by zemirco** [yahoo/react-intl#79] opened 2015-02-13 10:06 UTC
I'm using react with browserify and had some problems today with this nasty bug

> Uncaught TypeError: Cannot read property 'firstChild' of undefined
/~/react-router/~/react/lib/ReactMount.js?:606

Luckily I found the solution at [StackOverflow](http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined).

> For example, if you npm install a package that requires a different React version and puts it into dependencies instead of peerDependencies, it might install a separate React into node_modules/<some library using React>/node_modules/react.
Two different Reacts won't play nicely together (at least yet).

I removed `./node_modules/react-intl/node_modules/react` and now everything works fine again.

Please update your [package.json](https://github.com/yahoo/react-intl/blob/master/package.json) and move `react` to `peerDependencies`.

**Comment by caridy** [comment] 2015-02-13 13:43
@zemirco NPM can take care of de-duping the duplicated entries if the dependencies are correct. Make sure you are using a dependency at the app level that matches what we use in react-intl: `"react": ">=0.11.2 <0.13.0"`

**Comment by zemirco** [comment] 2015-02-13 13:55
I'm using `"react": "^0.12.2"`. Before that I used the new 0.13 beta and switched back. Maybe that caused the error.

**Comment by caridy** [comment] 2015-02-13 14:11
@zemirco cool, we will revisit the decision on the `peerDepedencies` vs `dependecies`, thanks for raising this issue.

**Comment by redonkulus** [comment] 2015-02-13 15:51
@caridy fyi that we did [something similar](https://github.com/yahoo/flux-router-component/pull/69) with flux-router-component.

**Comment by ericf** [comment] 2015-02-13 16:26
How would moving it to `peerDependencies` solve the problem? People would still be stuck if this package had a per-dep of `^0.12.0` when the developer wanted to use React `^0.13.0-beta1` in their app.

**Comment by caridy** [comment] 2015-02-13 16:43
@ericf it will at least throw the error, saying that npm cannot install a conflicting version. Right now, you just get into the `instanceOf` issues.

**Comment by ericf** [comment] 2015-02-13 16:46
Okay, so it sounds like we'll want:

```json
"peerDependencies": {
  "react": ">=0.11.2 <0.14.0"
}
```

**Comment by caridy** [comment] 2015-02-13 17:18
plus the devDep for our tests to function, and for our development workflow

**Comment by athibaud** [comment] 2015-02-19 10:26
just to chime in here. this is a common problem with any module which uses react.

if a dep is `require`d then it [must be a dependency](https://github.com/npm/npm/issues/5080#issuecomment-40545599). `peerDependencies` are only for modules which need the dep ~*implicitly* like express middleware (which never `require` express, but need to expose functions with `(req, res, next)` signature)

react-intl explicitly `require`s react and uses reacts' methods, therefore it *is* a dependency.

to have it as a `peerDependency` is incorrect. its the developers' responsibility to ensure you use the same versions of react and use `npm dedupe` to make sure you only have one version of react in your dependecy tree.

staying away from `peerDependencies` is a good idea. as we've experienced it [causes trouble with deeply `npm link`ed modules](https://github.com/npm/npm/issues/5080) and it will probably be renamed or deprecated..

**Comment by caridy** [comment] 2015-02-19 16:26
@athibaud we have had this discussion internally and externally in multiple occasions and with different folks. I disagree, I don't think putting the burden on devs is a good idea, it never is. `npm dedupe` can do nothing if the dependencies are explicit, and that's the primary feature of NPM. Also, I don't think `peerDependency` will be deprecated, time will tell if I'm wrong or not.

**Comment by hershmire** [comment] 2015-03-05 19:57
Is there a solution for handling this when using the latest React 0.13-alpha codebase?

**Comment by ericf** [comment] 2015-03-09 20:59
I'm changing my position on this. I want to keep it a [hard] dependency and **avoid** `peerDependencies`.

**Comment by ericf** [comment] 2015-03-09 22:58
This is only an issue right now because React's major version is < 1; once React hits 1.0, this goes away. Given that, and React's back-compat track record so far, I'm willing to open up the range to any React version `<1.0.0`. Once `react@1.0.0` is released, we'll move the range up to include `^1.0.0`.

**Closed** 2015-03-10 05:04 UTC
Labels: discussion, enhancement, support

**Comment by pedroteixeira** [comment] 2015-03-15 22:02
Can this changed be released? 

I'm having some trouble with `npm shrinkwrap` with react 0.13, and I think it's caused by react-intl:

```
npm WARN unmet dependency 
/node_modules/react-intl requires react@'>=0.11.2 <0.13.0' but will load
npm WARN unmet dependency /node_modules/react,
npm WARN unmet dependency which is version 0.13.0
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "node" "/usr/local/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v0.10.32
npm ERR! npm  v2.5.1

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: react@0.13.0 
/node_modules/react
```

**Comment by pedroteixeira** [comment] 2015-03-15 22:05
nevermind.. with npm 2.7.1 it worked (2.5.1 gives the error)

**Comment by ericf** [comment] 2015-03-17 17:54
[React Intl v1.2.0](https://github.com/yahoo/react-intl/releases/tag/v1.2.0) supports React v0.13+.
