### ISSUE TITLE
Safari compatibility?

### ISSUE THREAD

**Issue by Dindaleon** [yahoo/react-intl#342] opened 2016-03-01 19:48 UTC
Hello there, I am using `react-intl` on my sites but none of them work on safari unless I deactivate react-intl. Is there a step by step guide on how to make it compatible with safari?

I did try to load `intl` but still does not work.

```javascript
if (!global.Intl) {
  require.ensure([ 'intl' ], require => {
    require('intl');
    load();
  }, 'IntlBundle');
} else {
  load();
}
```

I updated it to this now:

```javascript
if (!global.Intl) {
  require.ensure([
    'intl',
    'intl/locale-data/jsonp/en.js',
    'intl/locale-data/jsonp/es.js',
    'intl/locale-data/jsonp/it.js'
  ], require => {
    require('intl');
    require('intl/locale-data/jsonp/en.js');
    require('intl/locale-data/jsonp/es.js');
    require('intl/locale-data/jsonp/it.js');
    addLocaleData(en);
    addLocaleData(es);
    addLocaleData(it);

    load();
  }, 'IntlBundle');
} else {
  load();
}
```

Still not working in Safari. What am I missing?
The error I get is `Failed to load resource: unsupported URL`

**Comment by ericf** [comment] 2016-03-01 21:00
> Still not working in Safari. What am I missing?
> The error I get is Failed to load resource: unsupported URL

Please provide more info.

What version of Safari, React, React Intl, Intl.js, etc.?
How does it not work?
What URL is failing to load?

**Comment by Dindaleon** [comment] 2016-03-01 21:12
Sure, sorry about that. Here is the info you requested: 

Safari 8.0
react: 0.14.3
react-intl: 2.0.0-beta-2
intl: 1.0.1

```
[Error] Failed to load resource: unsupported URL (main.js.map, line 0)
[Error] Failed to load resource: unsupported URL (core.js.map, line 0)
[Error] Failed to load resource: unsupported URL (utils.js.map, line 0)
[Error] Failed to load resource: unsupported URL (es5.js.map, line 0)
[Error] Failed to load resource: unsupported URL (compiler.js.map, line 0)
[Error] Failed to load resource: unsupported URL (parser.js.map, line 0)
[Error] Failed to load resource: unsupported URL (en.js.map, line 0)
[Error] Failed to load resource: unsupported URL (main.js.map, line 0)
[Error] Failed to load resource: unsupported URL (core.js.map, line 0)
[Error] Failed to load resource: unsupported URL (diff.js.map, line 0)
[Error] Failed to load resource: unsupported URL (es5.js.map, line 0)
[Error] Failed to load resource: unsupported URL (en.js.map, line 0)
[Error] Failed to load resource: unsupported URL (memoizer.js.map, line 0)
[Error] Failed to load resource: unsupported URL (es5.js.map, line 0)
[Error] Failed to load resource: unsupported URL (core.js.map, line 0)
[Error] Failed to load resource: unsupported URL (exp.js.map, line 0)
[Error] Failed to load resource: unsupported URL (cldr.js.map, line 0)
```

**Comment by ericf** [comment] 2016-03-01 21:20
So how do things not work? These are simply source mapping URL errors and can be ignored, this shouldn't cause any issues with the actual code running.

**Comment by moooji** [comment] 2016-03-01 21:30
In Safari, I get this error as soon as I require react-intl:

ReferenceError: Can't find variable: Intl
IntlProvider
mountComponent
ReactCompositeComponent_mountComponent

**Comment by ericf** [comment] 2016-03-01 21:38
> In Safari, I get this error as soon as I require react-intl:

@moooji that doesn't make sense if you're using 2.0.0-beta-2, the `Intl` built-ins are first accessed inside the `<IntlProvider>` constructor.

You need to polyfill Safari with the `Intl` APIs.

**Comment by ericf** [comment] 2016-03-01 21:39
Closing this, because 2.0.0-beta-2 has been tested and works in Safari. It can be reopened once there's a **simplified** and **reproducible** example of it failing.

**Closed by ericf** 2016-03-01 21:39 UTC
Labels: needs info, support

**Comment by Dindaleon** [comment] 2016-03-04 06:06
Hi there Eric, it might be too much to ask but if you ever get a chance, I would like you to check my repo at: http://github.com/dindaleon/hapi-react-starter-kit  The only way I have so far to make it work on safari is by disabling react-intl. Any help is greatly appreciated.
