### ISSUE TITLE
stringified messages paths not found

### ISSUE THREAD

**Issue by mschipperheyn** [yahoo/react-intl#54] opened 2014-12-30 18:12 UTC
When you use flat message files where the keys contains dots, they are not properly found. E.g.

	var i18n = {
		locales:['en'],
		messages:{
			ui:{
				wall: 'Wall',
				network:'Network',
				my:{
					mp:'My',
					fp:'My'
				},
				events:'Events'
			},
			calc:{
				calculators:'Calculators'
			},
			'ui.complete.profile':'Complete profile'
		}
	};

	module.exports = i18n;

if the key 'ui.complete.profile' is referenced, this will never be found because the library assumes a dot means a path. In our legacy applications that we are porting to React, all the message keys contain dots. I can imagine a script that converts these files to object structures, but I can also imagine a config-flag that allows you to set this path parsing as an option.

**Comment by caridy** [comment] 2015-01-13 20:08
duplicate of https://github.com/yahoo/react-intl/issues/46

**Closed by caridy** 2015-01-13 20:08 UTC
