### ISSUE TITLE
How to display 1minute 30 seconds ago"

### ISSUE THREAD

**Issue by rumsky** [yahoo/react-intl#1187] opened 2018-09-28 12:21 UTC
### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | VERSION |
| `npm ls react` | VERSION |
| `npm --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

| Browser | Version |
| --- | --- |
| NAME | VERSION |

**Comment by StorytellerCZ** [comment] 2018-09-28 14:33
Duplicate of #1188

**Closed** 2018-09-28 15:32 UTC
