### ISSUE TITLE
react-intl does not understand dot in resource-files keys

### ISSUE THREAD

**Issue by villesau** [yahoo/react-intl#118] opened 2015-06-05 08:32 UTC
Hello!

I would have the following kind of structure in my resource files:

smthng: {'login.tilte': 'Awesome title'}

anyhow the 'login.title' is not found by react-intl. This is quite important to have if you want to keep the resource file neat and readable, and the keys easily findable. Now it seems to assume, that dot represents always object structure, which might not be always the case.

**Comment by ericf** [comment] 2015-06-11 17:35
Is this when using the `this.getIntlMessage()` API?

**Comment by caridy** [comment] 2015-06-11 20:37
most likely a dupe of https://github.com/yahoo/react-intl/issues/46, closing.

**Closed by caridy** 2015-06-11 20:37 UTC
Labels: needs info
