### ISSUE TITLE
React 15.5.X

### ISSUE THREAD

**Issue by jonashartwig** [yahoo/react-intl#931] opened 2017-04-24 11:17 UTC
hi,

React 16 will remove React.PropTypes and React.createClass which are still used in react-intl 2.2.x and in the future react 16 will be removed completely. Maybe That can be updated?

Regards

**Comment by MichaelDeBoey** [comment] 2017-04-24 11:59
Dupe of #922, will be closed in #918

**Closed** 2017-04-24 13:09 UTC
