### ISSUE TITLE
main.js.map not found

### ISSUE THREAD

**Issue by ryexley** [yahoo/react-intl#96] opened 2015-03-18 13:27 UTC
I'm working on trying to integrate react-intl into an app I'm building...so far everything seems to be working well enough, but I've run into something I can't seem to figure out. When I run the app...everything runs fine, but in my browser console, I get a 404 not found on `main.js.map`. I have no idea where its expecting to get this source map file from...I can't even find it in the `node_modules` folder for the module. I'm building everything out with webpack...and am using CommonJS `require` functions for pulling everything in to the modules where I'm using it. I can provide more details if necessary, but...has anyone else run into this? Any idea what's going on?

**Comment by ryexley** [comment] 2015-03-18 14:42
So...follow up. I've been doing some digging, and it appears that there are sourceMap directives in the distributed files that references sourceMaps that aren't in the distributed package...like `main.js.map` referenced in `/lib/main.js`. Thats what it seems like from what I can tell. If that in fact is the case, it would be great to get that cleaned up...to eliminate the red herring console errors.

**Comment by ericf** [comment] 2015-03-18 15:10
This is a duplicate of #71.

**Closed by ericf** 2015-03-18 15:10 UTC
Labels: duplicate
