### ISSUE TITLE
Pass through style and className props to components

### ISSUE THREAD

**Issue by athibaud** [yahoo/react-intl#72] opened 2015-01-30 10:13 UTC
i often find myself needing to style (via style or className props) react-intl components
i see none of your components use the style or className props so far so i could submit a pull request to support that if you're fine with it.

**Comment by caridy** [comment] 2015-01-30 17:48
I don't fully understand what the problem is, but pull requests are always very welcome! 
https://github.com/yahoo/react-intl/blob/master/CONTRIBUTING.md

**Comment by ericf** [comment] 2015-01-30 18:54
@athibaud our recommendation is to wrap them in elements that you want to style instead of styling them directly. Basically to treat them the same as you would:

```jsx
<p>foo {this.props.bar}</p>
```

Where the fact that `this.props.bar` is wrapped in a `<span>` by React. So we'd like to thing of them as text node components. Could you provide an example of where you're not able to wrap the React Intl Components with other DOM nodes that you can style?

**Comment by athibaud** [comment] 2015-02-02 10:41
hello, sorry i was away for the weekend. thanks for replying.

@ericf fair enough. this makes sense for now.

this idea propped up from the other [issue](https://github.com/yahoo/react-intl/issues/73) i submitted. they kindof go hand in hand..
once you have the opportunity to wrap react-intl components in your own components you could also want to pass through props to that component. in our case its mostly the `style`prop but one could imagine any prop depending on that 'wrapper' component implementation..
so i now realise this idea has deeper implications than i originally thought so probably not a good idea anyway..

i opened these issue mostly for discussion, but seeing more and more people and doing css in js maybe just passing through the style props could be beneficial?

**Comment by athibaud** [comment] 2015-02-02 13:48
i think this issue could be renamed to 'transferProps' to react-intl components..
i realise this could cause collisions with the props that are used in the message but it should be the users problem to make sure there are no collisions. or maybe name-space these specific props in a `intlMessageProps` prop or something like that..

@ericf in your example
```js
<p>foo {this.props.bar}</p>
```
if you need to style the `span` that React generates for `{this.props.bar}` you would actually go ahead and wrap it in a `span`.
```js
<p>foo <span style={yourStyle}>{this.props.bar}</span></p>
```
and react won't create an extra `span` in the dom.. same goes for any prop like a `data`-attribute..

anyways, like i said, i opened this mostly for discussion..

**Comment by endragor** [comment] 2015-06-30 14:20
+1 to `className` prop support for react-intl components. I don't want my layout to be bloated with extra spans just for the sake of applying simple text styles to formatted messages.

**Comment by ericf** [comment] 2015-06-30 21:47
Closing this issue. The mental model is to think of the React Intl components as providing text, so to style the text you should wrap the components and provide your own styling.

**Closed by ericf** 2015-06-30 21:47 UTC
Labels: discussion

**Comment by scotchapman** [comment] 2016-05-24 15:58
I could see passing the style helping in development environments. Styling formatted text to distinguish between hardcoded text would be a nice visual check.

**Comment by ericf** [comment] 2016-05-24 19:03
@scotchapman if you're talking about messages that are missing translations, those already log warns to the console.

**Comment by amangeot** [comment] 2016-11-07 10:06
Hello, I am having an issue trying to pass styles to the wrapping span.

Let's say you have a form with an intl message such as "From {min} to {max}". Is it bad practice to use `FormattedMessage` to pass html `input`s as `min`, `max` ? The problem is aligning `input`s with the surrounding text. Passing some flex styles to the wrapper would do the job.

I thought there was some docs on how to style the wrapping span, but I can't find that doc anymore, if somebody could link it here, it would be great !

**Comment by ericf** [comment] 2016-11-08 21:12
@amangeot the escape hatch is to pass a function-as-child, then you get full control over rendering.

**Comment by amangeot** [comment] 2016-11-09 08:41
Function-as-child, thank you!

In case someone lands here, from: https://github.com/yahoo/react-intl/issues/162
```
let now = Date.now();

<FormattedDate value={now}>
    {(formattedNow) => (
        <time dateTime={now} className="fancy-date">{formattedNow}</time>
    )}
</FormattedDate>
```

**Comment by ericf** [comment] 2016-11-10 22:24
@amangeot here's a more complete example that formats `<time>`'s `dateTime` attribute properly: https://github.com/yahoo/react-intl/wiki/Upgrade-Guide#update-to-injectintl

**Comment by danielrob** [comment] 2017-09-19 03:06
Came across this working with third party provided css that wants to style my span elements and [span is the only legit no-op HTML element](https://stackoverflow.com/a/30795821/4682556).

Function as a child appears to still render inside a `<span>` tag. 

What's the harm in passing `style` and `className`? A bad pattern and we don't trust developers?  It's okay to say `FormatMessage` should be treated as text but the fact remains it's a span element containing text. It would be nice to have access to style that `span`. 

I was able to find a workaround by creating a larger translation string that was a combination of many smaller ones, and whose `tagName` was `"p"` instead.
