### ISSUE TITLE
Static (class) variables are lost when wrapping a component class with `injectIntl`.

### ISSUE THREAD

**Issue by fgoris** [yahoo/react-intl#379] opened 2016-03-29 20:55 UTC
If I define a component class (in ES6 syntax) like so:

```javascript
class MyComponent extends React.Component {

  static someStaticClassVariable = 42;

  ...

}
```

And then I wrap it:

```javascript
const MyIntlComponent = injectIntl(MyComponent);
```

The static variable is lost. If I try to access `someStaticClassVariable` on the new `MyIntlComponent` class, it will be `undefined`.

**Comment by ericf** [comment] 2016-03-29 23:21
Duplicate of #196

**Closed by ericf** 2016-03-29 23:21 UTC
