### ISSUE TITLE
FormattedMessage component doesn't pass on className, etc.

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [yahoo/react-intl#913] opened 2017-03-27 19:50 UTC
When using the component like:

```jsx
<FormattedMessage className='foo' id='xyz' defaultMessage='bar' />
```

I would expect the "foo" className to be applied, but it isn't. This makes it impossible to style a `FormattedMessage` using styled-components.

**Comment by ghostd** [comment] 2017-03-29 17:16
Hi,

This is a duplicate of #854

**Comment by okuryu** [comment] 2017-07-19 13:15
Duplicate of #854.

**Closed by okuryu** 2017-07-19 13:15 UTC
