### ISSUE TITLE
Question: rounding down currency formats

### ISSUE THREAD

**Issue by jphilipstevens** [yahoo/react-intl#262] opened 2015-12-23 20:58 UTC
Hey Everyone,

I want to be able to round down currency values to the nearest whole number. Is there a way to set the rounding for Intl.NumberFormat. I was looking at using a named format
"number": {
            "CAD": {
                "style": "decimal",
                "currency": "CAD",
                "maximumFractionDigits": 0
            }

So 649.72 would be 649

**Comment by ericf** [comment] 2015-12-24 05:56
What browser/node version are you seeing this in? Also, can you try to set style to `"currency"` and see if the issue is corrected?

**Comment by jphilipstevens** [comment] 2015-12-24 14:42
gah! I sent out a version where i was just poking the system to see how it works. 

I am now using currency but with the same effect. The browser i was testing on is Chrome 47

    "number": {
        "CAD": {
            "style": "currency",
            "currency": "CAD",
            "maximumFractionDigits": 0
    }

I ended up passing the price in after calling Math.floor

**Comment by ericf** [comment] 2015-12-24 15:24
Ah! This is a known Chrome bug. It should be fixed in 48 or 49.

**Closed by ericf** 2015-12-24 15:24 UTC
Labels: needs info

**Comment by jphilipstevens** [comment] 2015-12-24 15:27
Awesome. Thanks for clarifying! :)
