### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by scttnlsn** [yahoo/react-intl#71] opened 2015-01-25 15:16 UTC
Source map URLs are included in the source from NPM but I'm not sure the actual `.map` files are included (i.e. `lib/components/date.js` includes `//# sourceMappingURL=date.js.map`).

As a result I get the following when using `react-intl` (in Safari):

`Failed to load resource: The requested URL was not found on this server.` (referring to `date.js.map`)

**Comment by ericf** [comment] 2015-01-25 22:04
@scttnlsn Are you using Browserify or Webpack to bundle up `react-intl` with your app?

**Comment by scttnlsn** [comment] 2015-01-26 02:24
@ericf I'm using Browserify.  Let me know if there's any additional info I can provide.

**Comment by ericf** [comment] 2015-01-26 03:26
@scttnlsn So we have the source maps for these files, but we're not copying them over as part of the CommonJS build process. Do you happen to know if Browserify will automatically read in the input source maps and combine all of them for its bundling process?

In any case, [this is the line](https://github.com/yahoo/react-intl/blob/master/Gruntfile.js#L15) where we're not copying over the source maps for the CommonJS modules.

**Comment by gpbl** [comment] 2015-01-26 14:52
It would be nice to have the compiled files without the `//# sourceMappingURL` comment. Safari logs the missing .map file as error in the console, while Chrome seems to ignore it and displays the error in the Netwok activity. What about another grunt compile task, without [sourcemaps](https://github.com/yahoo/react-intl/blob/master/Gruntfile.js#L26)?

**Comment by scttnlsn** [comment] 2015-01-26 20:19
@ericf It's possible that Browserify will read input source maps (mentioned here: https://github.com/substack/node-browserify/issues/395) though I'm not sure if it is just limited to inline source maps.

**Comment by gitim** [comment] 2015-04-30 23:11
Have anybody solved this problem? It is still not clear for me how to use browserify in this case.

**Comment by prewk** [comment] 2015-07-14 08:59
We're getting these errors in Safari with webpack that must be related to the missing source maps:

![screenshot 2015-07-14 10 57 50](https://cloud.githubusercontent.com/assets/640102/8669735/417c943a-2a17-11e5-8dfc-6a11a6200c44.png)

**Comment by joshhornby** [comment] 2015-08-07 15:20
@prewk I am also seeing these issues. 

Did you find a fix?

**Comment by prewk** [comment] 2015-08-08 09:29
@joshhornby No, we're not developing in Safari so it's not a big problem atm.

Isn't your ReferenceError due to a missing polyfill?

`npm install intl` and then do a `require('intl');` at the top of your app entry point.

**Comment by drd** [comment] 2015-08-20 15:36
If you need Safari sourcemaps and you're using webpack, this kludge of a loader I wrote is an easy fix :)

https://www.npmjs.com/package/strip-sourcemap-loader

**Comment by prewk** [comment] 2015-08-20 18:17
@drd Thanks, that looks really useful! Might give it a go, would you mind throwing up a short README?

**Comment by Dindaleon** [comment] 2016-03-06 17:45
Any updates on this? I already have days trying to make react-intl work in safari. Any help is really appreciated.

**Comment by ericf** [comment] 2016-03-06 18:30
@Dindaleon this is fixed on master and will go out with the next release.

In the meantime you could always configure your build to pull in the `dist/react-intl.js` file instead.

**Closed by ericf** 2016-03-06 18:30 UTC
Labels: enhancement

**Comment by Dindaleon** [comment] 2016-03-06 19:34
Awesome Eric! Thank you and keep up the good work.

**Comment by mroswald** [comment] 2016-04-22 20:01
@ericf So, are you sure, the problem is fixed? I checked v2.1.0, but there are still sourceMappingUrls coming from `intl-messageformat` (and `intl`).

**Comment by ericf** [comment] 2016-04-22 21:48
@mroswald it was fixed in the `dist/` files, the `lib/` files pull in `intl-messageformat` from `node_modules/`. There's PRs open against all the `intl-*` packages to fix this, but I haven't had time to merge and release them. I will probably do it with an upgrade to CLDR 29.

In the meantime you could bundle `react-intl/dist/react-intl.min.js`.

**Comment by kunnix** [comment] 2016-10-21 01:05
Workaround to prevent webpack from pre-processing `node_modules/intl-*` js files with `source-map-loader`:

```
//  webpack.config.js

preLoaders: [
  {
    test: /\.js$/,
    exclude: /node_modules\/intl-/,
    loader: "source-map-loader"
  }
]
```
