### ISSUE TITLE
Formatted number not rendering correctly

### ISSUE THREAD

**Issue by aoshi321** [yahoo/react-intl#333] opened 2016-02-26 14:59 UTC
Hi

Im using the latest beta version and when I use the 'FormatNumber' as follows:
```
 <FormattedNumber value={1000} style="currency" currency="USD" />
```
It renders

1 000,00 $US

thanks

**Comment by ericf** [comment] 2016-02-26 17:13
What's the locale and browser, also what were you expecting?

You should try your combination of configuration options with [`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) and if you get the same result, then it's not a bug in this lib.

**Comment by ericf** [comment] 2016-03-02 16:30
Closing this for lack of information.

**Closed by ericf** 2016-03-02 16:30 UTC
Labels: needs info
